services:
  nginx:
    build: ../nginx
    ports:
      - "8080:80"
    restart: unless-stopped

  web:
    build: ../frontend
    volumes:
      - ../frontend/app:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: pnpm run dev
    restart: unless-stopped
    network_mode: "service:nginx"

  chat:
    build: ../chat-server
    volumes:
      - ../chat-server:/app
      - /app/node_modules
    environment:
      - PORT=3001
    restart: unless-stopped
    network_mode: "service:nginx"
